### ISSUE TITLE
使用了sav配置不生效

### ISSUE THREAD

**Issue by SusurHe** [Bluefissure/pal-conf#16]
我在liunx自建的server中使用了sav配置不生效

**Comment by Bluefissure** [comment]
1. 修改了哪些项目？哪些不生效？能够提供你生成的 `WorldOption.sav` ？
2. 是否有放入正确的位置？ `steamapps/common/PalServer/Pal/Saved/SaveGames/0/.../WorldOption.sav`
3. 是否在关闭服务器的情况下更新配置，然后重新启动？
