### ISSUE TITLE
大佬问下WorldOption.sav的服务器描述那里想要换行应该怎么写？

### ISSUE THREAD

**Issue by tubsevtu** [Bluefissure/pal-conf#20]
之前PalWorldSettings.ini里面我是用\n换的，现在想用sav格式的，但是发现网页里面打斜杠会被自动转义

**Comment by Bluefissure** [comment]
https://github.com/Bluefissure/pal-conf/commit/396f41db2bdad6fba9ded6c6f3f7ddaa6f756368 增加了支持，重新生成试试
