### ISSUE TITLE
关于 可采集物品生命值倍率 CollectionObjectHpRate 难易度

### ISSUE THREAD

**Issue by mcratt** [Bluefissure/pal-conf#29]
![1](https://github.com/Bluefissure/pal-conf/assets/37896943/5b24d892-1733-4f1c-a921-5341b59113aa)
在网上查找了下，有说法是矿物产出是固定的，产出多少取决于道具采集量倍率 CollectionDropRate ，因此可采集物品生命值倍率越高，装备耐久消耗就越大，帕鲁挖取时间就越久，所以是否数值越小，难度反更简单，越大反而更难呢？我现在玩把这个生命值倍率调大后，产出量感觉没什么增加。具体可能要大佬们测试下。

**Comment by Bluefissure** [comment]
不应该是 HP 越高一次刷新能获得的掉落越多吗？HP很低的话还没出几个就没掉要等下次刷新了

**Comment by mcratt** [comment]
我一开始也是这样想的，后面就把生命倍率改成3倍，然后在矿场挂机了一上午才1500+，才觉得不对劲，然后就网上找到了这种说法，然后现在改成0.5后，今天在矿场挂了一上午再多点时间，已经有快10000了。然后刚才看到你的回复，就去下载了服务器测试了下，不知道准不准确。
![生命倍率1](https://github.com/Bluefissure/pal-conf/assets/37896943/d5ee9304-24f9-4ead-bf04-9c2c081bc15d)
第一张图是生命倍率默认1，其他都没动。
![生命倍率3](https://github.com/Bluefissure/pal-conf/assets/37896943/8b559163-22f5-4ca4-be19-08c4f2c58adc)
第二张图是生命倍率3，其他也没动
![生命倍率0 5](https://github.com/Bluefissure/pal-conf/assets/37896943/8d84d6d2-1cac-4d66-a7db-cb524c7896fc)
第三张图是生命倍率0.5，其他没动
![生命倍率0 5 采集物倍率0 5](https://github.com/Bluefissure/pal-conf/assets/37896943/26bfec8f-0b84-449f-9faa-f4301cb8407e)
第四张图是生命倍率0.5，采集物掉率0.5（在测试到这里的时候，我本来把采集物掉率调到5倍，生命倍率还是0.5，但是发现矿石不刷新了，即便是日月速度调到了100倍，无奈之下只能去找另外一个同样大小的矿石得到这个结果。）
总共测试就是这样，在调好生命倍率后，我是把矿石打掉后生成一个新的再打才截的图，所以不会存在打的是上一个倍率的矿石问题，因为打3倍生命值的矿石比打1倍生命值的矿石费了更多时间，人是能感觉出来的，具体可能要其他大佬测试。

**Comment by Bluefissure** [comment]
感谢测试！等待片刻即会更新！
