### ISSUE TITLE
中文翻译优化

### ISSUE THREAD

**Issue by SlightDust** [Bluefissure/pal-conf#4]
感觉有些翻译不是很好理解，我先列出来一些修改建议，欢迎继续补充(x)
PalDamageRateAttack 帕鲁伤害率攻击 -> 帕鲁造成的伤害倍率  
PalDamageRateDefense 帕鲁伤害率防御 -> 帕鲁受到的伤害倍率
PlayerDamageRateAttack 玩家伤害率攻击 -> 玩家造成的伤害倍率  
PlayerDamageRateDefense 玩家伤害率防御 -> 玩家受到的伤害倍率

**Comment by Bluefissure** [comment]
参考游戏内的翻译进行了更新！ https://github.com/Bluefissure/pal-conf/commit/ea2de5cd4aec4867948dae96201de1269c3952f8
