### ISSUE TITLE
Update: PalWorld update some new server commands

### ISSUE THREAD

**Issue by APlayer2024** [Bluefissure/pal-conf#40]
Hi,
PalWorld update some new server commands
Please add it into https://pal-conf.bluefissure.com/
RESTAPIEnabled=False
RESTAPIPort=8212
AllowConnectPlatform=Steam
bIsUseBackupSaveData=True

**Comment by Bluefissure** [comment]
`RESTAPIEnabled`, `RESTAPIPort` and `bIsUseBackupSaveData` should be good to go after https://github.com/Bluefissure/pal-conf/commit/c7ccb80deb8602caea098f9de45f23f7d931069e .

`AllowConnectPlatform` is not working for the current version, will wait until then. (I also need to refactor the dropdown component https://github.com/Bluefissure/pal-conf/issues/41)
