### ISSUE TITLE
[Question] BaseCampWorkerMaxNum or BaseCampMaxWorkerNum ??

### ISSUE THREAD

**Issue by Bluefissure** [Bluefissure/pal-conf#42]
It used to be `BaseCampWorkerMaxNum` but in the [new tech guide](https://tech.palworldgame.com/settings-and-operation/configuration/#parameters), it's `BaseCampMaxWorkerNum`, which one works? Or they both work?

**Comment by Souma-Sumire** [comment]
❌ `BaseCampMaxWorkerNum` is invalid.

✅ `BaseCampWorkerMaxNum` is valid.
