### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by Azzlaer** [Bluefissure/pal-conf#47]
Al utilizar mi PalWorldSettings en tu pagina este dice un error:
**The settings you pasted have been loaded. But some settings are missing.**

La pagina web necesita actualizacion :)

**Comment by Bluefissure** [comment]
Please upload the settings you pasted here so I can check. (Remember to mask out your credential info.)

**Comment by dkoz** [comment]
Here are some of the missing settings.
- `LogFormatType` - `Text`/`Json` statement.
  - Changes console log format output.
- `AllowConnectPlatform` - `Xbox`/`Steam`
  - The release of console servers makes this actually needed.

**Comment by Bluefissure** [comment]
Should be updated https://github.com/Bluefissure/pal-conf/commit/3f2efd50a6974e14827840052caa33147fa7a556
