### ISSUE TITLE
Version 0.4.11 configuration file update

### ISSUE THREAD

**Issue by duxdyu** [Bluefissure/pal-conf#52]
The update announcement contains these two items:
You can now set "Maximum number of buildings per base" in the world settings.
The weight multiplier for all items can now be changed in world settings.

**Comment by dkoz** [comment]
I have pull request open right now with all the new settings. Just need to wait for Bluefissure.

**Comment by Bluefissure** [comment]
It should be updated now, thanks @dkoz !

**Comment by duxdyu** [comment]
nice！
